runs:
  using: "composite"
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: NextJS Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/packages/app/.next/cache
        key: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ '**/pnpm-lock.yaml' }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
