export const RESERVED_KEYS = new Set([
    "api",
    "static",
    "stats",
    "proxy",
    "auth",
    "pricing",
    "about",
    "metatags",
    "careers",
    "features",
    "contact",
    "terms",
    "privacy",
    "admin",
    "help",
    "new",
]);

// "github",
//     "instagram",
//     "facebook",
//     "linkedin",
//     "discord",
//     "radu",
//     "bear",
//     "ruggedbear",
//     "radudotgg",
//     "rcp",
